(try)
(try (catch Symbol name))
(try (finally))
(try (catch Symbol name) (finally))
(try (catch Symbol name) (catch Symbol name) (finally))

(try ())
(try () (catch Symbol name 2))
(try () (finally 3))
(try () (catch Symbol name 2) (finally 3))
(try () (catch Symbol name 2) (catch Symbol name 2) (finally 3))

(try () 1)
(try () 1 (catch Symbol name (a) [4]))
(try () 1 (finally "b" :c))
(try () 1 (catch Symbol name (a) [4]) (finally "b" :c))
(try () 1 (catch Symbol name (a) [4]) (catch Symbol name (a) [4]) (finally "b" :c))
